/* jshint -W014, -W033, esversion: 9 */
/* eslint-disable new-cap */
'use strict'

module.exports = {
  accNotFound: 'accessory not found',
  addInfo: 'additional info',
  cfgDef: 'is not a valid number so using default of',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  chargeFail: 'sending charge update failed as',
  cleanFail: 'sending clean update failed as',
  cleaning: 'cleaning',
  complete: '✓ Setup complete',
  curBatt: 'current battery',
  curCharging: 'current charging state',
  curCleaning: 'current cleaning state',
  curCommand: 'current command',
  curSpeed: 'current cleaning speed',
  devAdd: 'has been added to Homebridge',
  deviceListFail: 'could not retrieve devices from ECOVACS',
  devInit: 'initialised with id',
  devInitOpts: 'initialising with options',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotInit: 'could not be initialised as',
  devNotRef: 'could not be refreshed as',
  devNotRemove: 'could not be removed from Homebridge as',
  devRemove: 'has been removed from Homebridge',
  disabled: 'To change this, set disablePlugin to false',
  disabling: 'Disabling plugin',
  ecovacsLibVersion: 'Using ecovacs-deebot library',
  errNotInit: 'device has not initialised device yet',
  errNotReady: 'device is not ready to accept commands',
  hbVersionFail: 'Your version of Homebridge is too low - please update to v1.3',
  identify: 'identify button pressed',
  inBattFail: 'receiving battery update failed as',
  inChgFail: 'receiving charge update failed as',
  inClnFail: 'receiving clean update failed as',
  inErrFail: 'receiving error update failed as',
  inSpdFail: 'receiving speed update failed as',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  inMsgFail: 'receiving message update failed as',
  inRdyFail: 'receiving ready update failed as',
  invalidCCode: 'Invalid ECOVACS country code',
  invalidPassword: 'Invalid ECOVACS password',
  invalidUsername: 'Invalid ECOVACS username',
  lowBattMsg: 'Device has low battery - ',
  missingCreds: 'ECOVACS credentials missing from config',
  pluginNotConf: 'Plugin has not been configured',
  receiveCmd: 'receiving update',
  repOffline: 'has been reported [offline]',
  repOnline: 'has been reported [online]',
  returning: 'returning',
  sendCmd: 'sending update',
  sentMsg: 'sent message',
  sentErr: 'sent error',
  speedFail: 'sending speed update failed as',
  stop: 'stop',
  zWelcome: [
    "Don't forget to ☆ this plugin on GitHub if you're finding it useful!",
    'Have a feature request? Visit http://bit.ly/hb-deebot-issues to ask!',
    'Interested in sponsoring this plugin? https://github.com/sponsors/bwp91',
    "Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW",
    'Thanks for using this plugin, I hope you find it helpful!',
    'This plugin has been made with ♥ by bwp91 from the UK!',
    'Have time to give this plugin a review? http://bit.ly/hb-deebot-review',
    'Want to see this plugin in your own language? Let me know!'
  ]
}
