export default {
  accNotFound: 'accessory not found',
  accNotReady: 'cannot currently be controlled, see plugin startup logs for any error',
  addInfo: 'additional info',
  airDryingFail: 'sending air drying update failed as',
  cfgDef: 'is not a valid number so using default of',
  cfgDup: 'will be ignored since another entry with this ID already exists',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  chargeFail: 'sending charge update failed as',
  cleanFail: 'sending clean update failed as',
  cleaning: 'cleaning',
  characteristicsReset: 'characteristic values reset to 0',
  commandForArea: 'Command for predefined area',
  commandSent: 'command was sent',
  complete: '✓ Setup complete',
  curAirDrying: 'current air drying state',
  curArea: 'current predefined area',
  curBatt: 'current battery',
  curCharging: 'current charging state',
  curCleaning: 'current cleaning state',
  curSpeed: 'current cleaning speed',
  devAdd: 'has been added to Homebridge',
  deviceCount: 'device(s) found in your ECOVACS account',
  deviceListFail: 'could not retrieve devices from ECOVACS',
  devInit: 'initialised with id',
  devInitOpts: 'initialising with options',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotInit: 'could not be initialised as',
  devNotRef: 'could not be refreshed as',
  devNotRemove: 'could not be removed from Homebridge as',
  devRemove: 'has been removed from Homebridge',
  disabled: 'To change this, set disablePlugin to false',
  disabling: 'Disabling plugin',
  ecovacsLibVersion: 'Using ecovacs-deebot library',
  errNotInit: 'device has not initialised device yet',
  errNotReady: 'device is not ready to accept commands',
  hbVersionFail: 'Your version of Homebridge is too low - please update to v1.5',
  inAirFail: 'receiving air drying update failed as',
  inBattFail: 'receiving battery update failed as',
  inChgFail: 'receiving charge update failed as',
  inClnFail: 'receiving clean update failed as',
  inErrFail: 'receiving error update failed as',
  inSpdFail: 'receiving speed update failed as',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  inMsgFail: 'receiving message update failed as',
  inRdyFail: 'receiving ready update failed as',
  invalidCCode: 'Invalid ECOVACS country code',
  invalidPassword: 'Invalid ECOVACS password',
  invalidUsername: 'Invalid ECOVACS username',
  lowBattMsg: 'Device has low battery - ',
  missingCreds: 'ECOVACS credentials missing from config',
  noCommandForArea: 'returning no command for predefined area',
  noTypeForArea: 'returning no type for predefined area',
  oldCommandFound: 'Old command (<= release 5.1.0) found for predefined area',
  pluginNotConf: 'Plugin has not been configured',
  receiveCmd: 'receiving update',
  repOffline: 'has been reported [offline]',
  repOnline: 'has been reported [online]',
  returning: 'returning',
  returningAsValueNull: 'returning as value === 0',
  sendCmd: 'sending update',
  sentErr: 'sent error',
  sentMsg: 'sent message',
  skippingValue: 'skipping old value as new value noticed',
  speedFail: 'sending speed update failed as',
  stop: 'stop',
  typeForArea: 'Type for predefined area',
  unknownCommandTypeForArea: 'Unknown command type for predefined area',
  zWelcome: [
    'Don\'t forget to ☆ this plugin on GitHub if you\'re finding it useful!',
    'Have a feature request? Visit https://bit.ly/hb-deebot-issues to ask!',
    'Interested in sponsoring this plugin? https://github.com/sponsors/bwp91',
    'Join the plugin\'s Discord community! https://discord.gg/cMGhNtZ3tW',
    'Thanks for using this plugin, I hope you find it helpful!',
    'This plugin has been made with ♥ by bwp91 from the UK!',
    'Check out my other Homebridge plugins! https://github.com/bwp91',
    'Have time to give this plugin a review? https://bit.ly/hb-deebot-review',
    'This plugin needs it\'s first ☆ rating on HOOBS! https://bit.ly/hb-deebot-review',
    'Want to see this plugin in your own language? Let me know!',
    'This plugin gratefully uses the ecovacs-deebot client by @mrbungle64! https://github.com/mrbungle64',
  ],
};
